--- 
    hosts: webservers
    become: yes
    tasks:
     - name: ensure apache is at the latest version
       yum:
         name: http
         state: latest
     - name: ensure apache is running
       services:
         name: http
         state: started
      
      

    